name: Build Artifact

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DoombubblesPlugins
          path: DoombubblesPlugins/

      - name: Zip for release
        if: startsWith(github.ref, 'refs/tags/')
        run: zip -r DoombubblesPlugins.zip DoombubblesPlugins/

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          files: DoombubblesPlugins.zip
          generate_release_notes: true
          body_path: LATEST.md
